-- ============================================================
-- FITNESS APP — DATABASE SCHEMA
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ============================================================
-- PROFILES
-- Extends Supabase auth.users with app-specific data
-- ============================================================
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  name         text,
  created_at   timestamptz default now()
);

-- Auto-create a profile row when a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- GOALS
-- User's current training goal (one active at a time)
-- ============================================================
create table public.goals (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references public.profiles(id) on delete cascade,
  type           text not null check (type in ('build_muscle', 'lose_weight', 'endurance', 'general_fitness')),
  created_at     timestamptz default now()
);

-- ============================================================
-- USER PREFERENCES
-- Training preferences collected during onboarding
-- ============================================================
create table public.user_preferences (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null unique references public.profiles(id) on delete cascade,
  days_per_week       int not null check (days_per_week between 2 and 6),
  experience_level    text not null check (experience_level in ('beginner', 'intermediate', 'advanced')),
  equipment           text[] not null default '{}',  -- e.g. ['barbell', 'dumbbells', 'cables', 'bodyweight']
  program_length_weeks int not null default 6 check (program_length_weeks in (6, 8)),
  updated_at          timestamptz default now()
);

-- ============================================================
-- EXERCISES
-- Master list — seeded defaults + user custom exercises
-- ============================================================
create table public.exercises (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references public.profiles(id) on delete cascade,  -- null = global/default
  name          text not null,
  muscle_group  text not null check (muscle_group in (
                  'chest', 'back', 'shoulders', 'biceps', 'triceps',
                  'legs', 'glutes', 'core', 'cardio', 'full_body'
                )),
  equipment     text not null check (equipment in (
                  'barbell', 'dumbbells', 'cables', 'machine',
                  'bodyweight', 'kettlebell', 'bands', 'cardio_machine'
                )),
  is_custom     boolean not null default false,
  created_at    timestamptz default now(),
  unique (user_id, name)
);

-- ============================================================
-- PROGRAMS
-- A 6 or 8 week training program generated by AI
-- ============================================================
create table public.programs (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles(id) on delete cascade,
  goal_id       uuid references public.goals(id),
  name          text not null,
  weeks         int not null check (weeks in (6, 8)),
  start_date    date,
  status        text not null default 'active' check (status in ('active', 'completed', 'paused')),
  created_at    timestamptz default now()
);

-- ============================================================
-- PROGRAM DAYS
-- Each day in the program (week 1 day 1, week 1 day 2, etc.)
-- ============================================================
create table public.program_days (
  id            uuid primary key default gen_random_uuid(),
  program_id    uuid not null references public.programs(id) on delete cascade,
  week_number   int not null,
  day_number    int not null,
  label         text not null,   -- e.g. "Push Day", "Pull Day", "Legs"
  unique (program_id, week_number, day_number)
);

-- ============================================================
-- PROGRAM EXERCISES
-- The prescribed sets/reps/weight for each exercise in a day
-- Updated by the progressive overload engine each week
-- ============================================================
create table public.program_exercises (
  id              uuid primary key default gen_random_uuid(),
  program_day_id  uuid not null references public.program_days(id) on delete cascade,
  exercise_id     uuid not null references public.exercises(id),
  order_index     int not null default 0,
  target_sets     int not null,
  target_reps     text not null,   -- stored as string e.g. "8-12" or "10"
  target_weight   numeric,         -- null = bodyweight or to be determined
  notes           text             -- AI reasoning for this prescription
);

-- ============================================================
-- WORKOUT LOGS
-- Records a completed workout session for a program day
-- ============================================================
create table public.workout_logs (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.profiles(id) on delete cascade,
  program_day_id  uuid references public.program_days(id),
  date            date not null default current_date,
  duration_mins   int,
  overall_feeling int check (overall_feeling between 1 and 5),  -- 1=terrible 5=great
  notes           text,
  created_at      timestamptz default now()
);

-- ============================================================
-- WORKOUT SETS
-- Individual sets logged during a workout
-- ============================================================
create table public.workout_sets (
  id              uuid primary key default gen_random_uuid(),
  workout_log_id  uuid not null references public.workout_logs(id) on delete cascade,
  exercise_id     uuid not null references public.exercises(id),
  set_number      int not null,
  reps_done       int not null,
  weight_done     numeric not null default 0,  -- in lbs
  created_at      timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- Users can only read/write their own data
-- ============================================================
alter table public.profiles         enable row level security;
alter table public.goals            enable row level security;
alter table public.user_preferences enable row level security;
alter table public.exercises        enable row level security;
alter table public.programs         enable row level security;
alter table public.program_days     enable row level security;
alter table public.program_exercises enable row level security;
alter table public.workout_logs     enable row level security;
alter table public.workout_sets     enable row level security;

-- Profiles
create policy "Users can view own profile"   on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Goals
create policy "Users manage own goals" on public.goals for all using (auth.uid() = user_id);

-- Preferences
create policy "Users manage own preferences" on public.user_preferences for all using (auth.uid() = user_id);

-- Exercises: see global exercises + own custom ones
create policy "Users see global and own exercises" on public.exercises
  for select using (user_id is null or auth.uid() = user_id);
create policy "Users manage own exercises" on public.exercises
  for all using (auth.uid() = user_id);

-- Programs
create policy "Users manage own programs" on public.programs for all using (auth.uid() = user_id);

-- Program days (accessible if user owns the program)
create policy "Users see own program days" on public.program_days
  for select using (
    exists (select 1 from public.programs p where p.id = program_id and p.user_id = auth.uid())
  );

-- Program exercises
create policy "Users see own program exercises" on public.program_exercises
  for select using (
    exists (
      select 1 from public.program_days pd
      join public.programs p on p.id = pd.program_id
      where pd.id = program_day_id and p.user_id = auth.uid()
    )
  );

-- Workout logs
create policy "Users manage own workout logs" on public.workout_logs for all using (auth.uid() = user_id);

-- Workout sets
create policy "Users manage own workout sets" on public.workout_sets
  for all using (
    exists (select 1 from public.workout_logs wl where wl.id = workout_log_id and wl.user_id = auth.uid())
  );

-- ============================================================
-- SEED — DEFAULT EXERCISES
-- A starter library; user can add more from their Google Drive list
-- ============================================================
insert into public.exercises (name, muscle_group, equipment, is_custom) values
  -- Chest
  ('Barbell Bench Press',       'chest',     'barbell',   false),
  ('Incline Dumbbell Press',    'chest',     'dumbbells', false),
  ('Cable Chest Fly',           'chest',     'cables',    false),
  ('Push-Up',                   'chest',     'bodyweight',false),
  ('Dumbbell Bench Press',      'chest',     'dumbbells', false),
  -- Back
  ('Pull-Up',                   'back',      'bodyweight',false),
  ('Barbell Row',               'back',      'barbell',   false),
  ('Seated Cable Row',          'back',      'cables',    false),
  ('Lat Pulldown',              'back',      'cables',    false),
  ('Dumbbell Row',              'back',      'dumbbells', false),
  -- Shoulders
  ('Overhead Press',            'shoulders', 'barbell',   false),
  ('Dumbbell Lateral Raise',    'shoulders', 'dumbbells', false),
  ('Face Pull',                 'shoulders', 'cables',    false),
  ('Dumbbell Shoulder Press',   'shoulders', 'dumbbells', false),
  -- Biceps
  ('Barbell Curl',              'biceps',    'barbell',   false),
  ('Dumbbell Curl',             'biceps',    'dumbbells', false),
  ('Cable Curl',                'biceps',    'cables',    false),
  ('Hammer Curl',               'biceps',    'dumbbells', false),
  -- Triceps
  ('Tricep Dip',                'triceps',   'bodyweight',false),
  ('Cable Pushdown',            'triceps',   'cables',    false),
  ('Skull Crusher',             'triceps',   'barbell',   false),
  ('Overhead Tricep Extension', 'triceps',   'dumbbells', false),
  -- Legs
  ('Barbell Squat',             'legs',      'barbell',   false),
  ('Romanian Deadlift',         'legs',      'barbell',   false),
  ('Leg Press',                 'legs',      'machine',   false),
  ('Leg Curl',                  'legs',      'machine',   false),
  ('Leg Extension',             'legs',      'machine',   false),
  ('Dumbbell Lunge',            'legs',      'dumbbells', false),
  ('Bulgarian Split Squat',     'legs',      'dumbbells', false),
  -- Glutes
  ('Hip Thrust',                'glutes',    'barbell',   false),
  ('Cable Kickback',            'glutes',    'cables',    false),
  -- Core
  ('Plank',                     'core',      'bodyweight',false),
  ('Cable Crunch',              'core',      'cables',    false),
  ('Hanging Leg Raise',         'core',      'bodyweight',false),
  -- Full Body
  ('Deadlift',                  'full_body', 'barbell',   false),
  ('Kettlebell Swing',          'full_body', 'kettlebell',false);
